services:
  my-db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: test
    volumes:
      - ./mysql_data:/var/lib/mysql
    ports:
      - 3306:3306

  redis-local:
    image: redis
    ports:
      - 6379:6379

