name: Slack Notify
on:
  workflow_call:
    inputs:
      status:
        required: true
        type: string
jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Slack notification (success or failure)
        uses: 8398a7/action-slack@v3
        with:
          mention: ${{ inputs.status == 'failure' && 'here' || '' }}
          if_mention: failure
          status: ${{ inputs.status }}
          fields: workflow,job,commit,message,ref,author,took
          text: |
            ${{ inputs.status == 'success' && ':tada: 배포 성공!' || ':x: 배포 실패!' }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
